version: '3.1'
services:
    website:
        image: php:apache
        container_name: webapp
        depends_on:
            - api
        ports:
            - "8585:80"
        volumes: 
            - ./website:/var/www/html
        networks:
            - webapp_network
    api: 
        image: studentslistapi:v1
        container_name: apistudentslist
        ports:
            - "6000:5000"
        volumes:
            - ./simple_api/student_age.json:/data/student_age.json
        networks:
            - webapp_network
networks:
  webapp_network:
    driver: bridge
